### https://docs.pi-hole.net/
### https://github.com/pi-hole/docker-pi-hole/
### https://github.com/pi-hole/docker-pi-hole#note-on-capabilities

services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      # ServerIP: ???
      # WEBPASSWORD: YourPiholePassword
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      DNSMASQ_LISTENING: all ### "Permit all origins"
    ports:
      - 53:53/tcp ### Yes, it is actually required to specify tcp & udp
      - 53:53/udp
      - 8053:80
    volumes:
      - etc-pihole:/etc/pihole/
      - etc-dnsmasq-d:/etc/dnsmasq.d/
      - ./conf/a_records.conf:/etc/pihole/custom.list
      - ./conf/c_names.conf:/etc/dnsmasq.d/05-pihole-custom-cname.conf
      - ./conf/resolv.conf:/etc/resolv.conf ### nameserver 127.0.0.1
    restart: always

volumes:
  etc-pihole:
  etc-dnsmasq-d:
