### https://docs.pi-hole.net/
### https://github.com/pi-hole/docker-pi-hole/
### https://github.com/pi-hole/docker-pi-hole#note-on-capabilities

version: "3.8"

services:
  pihole:
    container_name: homelab_pihole
    image: pihole/pihole  
    environment:
      # ServerIP: 
      WEBPASSWORD: YourPiholePassword
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      DNSMASQ_LISTENING: all
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    volumes:
      - etc-pihole:/etc/pihole/
      - etc-dnsmasq-d:/etc/dnsmasq.d/
      # - ./conf/setupVars.conf:/etc/pihole/setupVars.conf
      - ./conf/custom.list:/etc/pihole/custom.list
      - ./conf/05-pihole-custom-cname.conf:/etc/dnsmasq.d/05-pihole-custom-cname.conf
    cap_add:
      - NET_ADMIN # Only required if you are using Pi-hole as your DHCP server
    restart: unless-stopped

volumes:
  etc-pihole:
  etc-dnsmasq-d:
