### https://docs.pi-hole.net/
### https://github.com/pi-hole/docker-pi-hole/
### https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
### https://www.reddit.com/r/pihole/comments/1iu6iil/local_dns_records_not_working_anymore_after/

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      PIHOLE_UID: "1000"
      PIHOLE_GID: "1000"
      TZ: Australia/Melbourne
      # FTLCONF_webserver_api_password: correct horse battery staple
      FTLCONF_dns_listeningMode: all
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1
      FTLCONF_dns_piholePTR: None
      # DNSMASQ_USER: root
      FTLCONF_dns_hosts: 1.1.1.1 asd.asd;2.2.2.2 jahsdas.akhda
      FTLCONF_misc_etc_dnsmasq_d: "true"
      FTLCONF_misc_dnsmasq_lines: address=/greyman.space/10.1.1.180
    ports:
      - 53:53/tcp ### Yes, it is actually required to specify tcp & udp
      - 53:53/udp
      - 8053:80/tcp
      # - 8054:443/tcp
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
      - ./conf/a_records.conf:/etc/pihole/custom.list
    restart: unless-stopped
