### https://docs.pi-hole.net/
### https://github.com/pi-hole/docker-pi-hole/
### https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
### https://www.reddit.com/r/pihole/comments/1iu6iil/local_dns_records_not_working_anymore_after/

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      PIHOLE_UID: "1000"
      PIHOLE_GID: "1000"
      TZ: Australia/Melbourne
      # FTLCONF_webserver_api_password: correct horse battery staple
      FTLCONF_dns_listeningMode: all
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1
      FTLCONF_dns_piholePTR: None ### Troubleshoot local DNS
      DNSMASQ_USER: root ### Troubleshoot local DNS
      FTLCONF_dns_domain: galea.lan
      FTLCONF_dns_hosts: |
        10.1.1.1 pfsense.galea.lan
        10.1.1.2 prox.galea.lan
        10.1.1.5 printer.galea.lan
        10.1.1.102 bookstack.galea.lan
        10.1.1.110 unifi.galea.lan
        10.1.1.130 torrents.galea.lan
        10.1.1.150 csgo.galea.lan
        10.1.1.152 emby.galea.lan
        10.1.1.153 minecraft.galea.lan
        10.1.1.154 tmf.galea.lan
        10.1.1.155 wekan.galea.lan
        10.1.1.181 jenkins.galea.lan
        10.1.1.210 docker.galea.lan
      # 10.1.1.101 pihole-old.galea.lan
      # 10.1.1.104 radarr.galea.lan
      # 10.1.1.105 sonarr.galea.lan
      # 10.1.1.106 lidarr.galea.lan
      # 10.1.1.107 qbittorrent.galea.lan
      # 10.1.1.108 jackett.galea.lan
      # 10.1.1.109 bazarr.galea.lan
      # 10.1.1.114 jellyfin.galea.lan
      # 10.1.1.160 scraper.galea.lan
      # 10.1.1.180 nginx.galea.lan
      FTLCONF_misc_etc_dnsmasq_d: "true"
      # FTLCONF_misc_dnsmasq_lines: address=/greyman.space/10.1.1.180
      FTLCONF_misc_dnsmasq_lines: address=/greyman.space/10.1.1.210
    ports:
      - 53:53/tcp ### Yes, it is actually required to specify tcp & udp
      - 53:53/udp
      - 8053:80/tcp
      # - 8054:443/tcp
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped
